[project]
name = "cli-automation"
version = "1.5.0"
description = "Network Automation from the Command Line"
authors = [
    {name = "Ed Scrimaglia",email = "edgardo.scrimaglia@gmail.com"}
]
keywords = ["networking", "automation", "typer", "cli", "python"]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10, <4.0"
dependencies = [
    "typer (>=0.15.1,<0.16.0)",
    "pydantic (>=2.10.6,<3.0.0)",
    "rich (>=13.9.4,<14.0.0)",
    "netmiko (==4.5.0)",
    "aiofiles (>=24.1.0,<25.0.0)",
    "ntc-templates (>=1.1.0,<8.0.0)",
    "textfsm (>=1.1.0,<2.0.0)",
    "paramiko (>=2.6.0,<4.0.0)",
    "pysocks (>=1.7.1,<2.0.0)",
    "requests (>=2.32.3,<3.0.0)"
]

[project.scripts]
cla="cli_automation.main:app"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
