[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "an_condamanager"
version = "1.2.2"
description = "A package for an_condamanager."
authors = [
    { name = "Atsushi888", email = "vtgrotxu@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.6"
dependencies = ['an_DebugHelper>=1.3.3', 'an_CudaUtility', 'an_QuickViper2', 'an_UniqueEnvVar', 'an_EasyVen', 'an_ToolKit']

[project.urls]
Homepage = "https://github.com/Atsushi888/an_condamanager"
Repository = "https://github.com/Atsushi888/an_condamanager"
