[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quant-drl-core"  # Este serÃ¡ el nombre visible en PyPI
version = "0.1.0"
description = "Deep Reinforcement Learning for Financial Portfolio Management"
authors = [
  { name="Pablo Diego Acosta", email="pablodieaco@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"

dependencies = [
  "numpy==2.0.0",
  "pandas==2.2.3",
  "pandas_market_calendars==4.6.1",
  "gym==0.23.0",
  "matplotlib==3.9.0",
  "stable-baselines3==2.5.0",
  "scikit-learn==1.6.1",
  "loguru==0.7.3",
  "tqdm==4.66.1",
  "tensorflow==2.19.0",
  "tensorboard==2.19.0",
  "torch==2.6.0",
  "plotly==6.0.0",
  "seaborn==0.13.2",
  "yfinance==0.2.54",
  "ta==0.11.0",
]

[project.urls]
"Homepage" = "https://github.com/pablodieaco/quant-drl-core"
"Repository" = "https://github.com/pablodieaco/quant-drl-core"
"Issues" = "https://github.com/pablodieaco/quant-drl-core/issues"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
