[project]
name = "staygreen"
version = "0.3.2"
description = "Stay green"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyautogui>=0.9.54",
]

[project.urls]
Homepage = "https://codeberg.org/berk76/stay-green"
Repository = "https://codeberg.org/berk76/stay-green"
Issues = "https://codeberg.org/berk76/stay-green/issues"

[project.scripts]
klepadlo = "staygreen.green:main"
test01 = "staygreen.green:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = [
    "staygreen/*",
]
