[build-system]
requires = ["setuptools>=61.0", "toml"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-admin-cli"
version = "0.4.5"
description = "Django-inspired CLI for FastAPI applications"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "typer>=0.4.0",
    "jinja2>=3.0.0",
    "uvicorn>=0.15.0",
    "toml>=0.10.2",
    "gitpython>=3.1.30",
]
[[project.authors]]
name = "Amal Babu"
email = "developer.amalbabu@gmail.com"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "ruff>=0.0.292",
    "build>=0.10.0",
    "twine>=4.0.0",
    "toml>=0.10.2",
]

[project.scripts]
fastapi-admin = "fastapi_admin.cli:run_from_command_line"
create-template-structure = "scripts.create_template_structure:create_template_structure"

[project.urls]
Homepage = "https://github.com/amal-babu-git/fastapi-admin-cli"
"Bug Tracker" = "https://github.com/amal-babu-git/fastapi-admin-cli/issues"

[tool.setuptools]
packages = ["fastapi_admin", "fastapi_admin.commands", "fastapi_admin.utils", "scripts"]
include-package-data = true

[tool.ruff]
line-length = 100
target-version = "py38"
select = ["E", "F", "I", "W"]
ignore = []

[tool.setuptools.package-data]
fastapi_admin = ["templates/**/*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
