[project]
name = "hive-chat"
dynamic = ["version"]
authors = [{ name = "Gary Benson", email = "gary@gbenson.net" }]
description = "Chatbot interface for Hive"
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "cloudevents[pydantic]",
    "hive-common>=0.1.1",
    "hive-messaging>=0.12.5",
]

[project.urls]
Homepage = "https://github.com/gbenson/hive/tree/main/libs/chat"
Source = "https://github.com/gbenson/hive"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "hive.chat.__version__.__version__"}

[tool.pytest.ini_options]
addopts = "--cov=hive.chat"

[tool.coverage.run]
omit = [
    "*/venv/*",
    "*/.venv/*",
]

[tool.coverage.report]
skip_covered = true
