[tool.poetry]
name = "agent_guard_core"
version = "0.1.3"
description = "Python library to secure AI agents with environment credentials from multiple secret providers and more"
readme = "README.md"
license = "Apache Software License (Apache-2.0)"
authors = ["CyberArk <acyberark@cyberark.com>"]
packages = [
    { include = "agent_guard_core" },
]


[tool.semantic_release.main]
branch = "main"
version_variable = ["pyproject.toml:version"]
upload_to_pypi = false
upload_to_release = true
build_command = "pip install poetry && poetry build"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.10.0, <4.0"
boto3 = "*"
python-dotenv = "^1.0.1"
requests = "^2.32.3"

[tool.poetry.dev-dependencies]
pytest = "*"
yapf = "^0.43.0"
isort = "^6.0.1"
autoflake = "^2.3.1"
toml = "^0.10.2"
twine = "^6.1.0"
python-semantic-release = "^9.21.0"
bandit = "^1.8.3"

[tool.poetry.group.aws.dependencies]
boto3 = "*"

[tool.poetry.group.autogen.dependencies]
autogen-core = ">=0.4.9.2,<0.5.0.0"
autogen-ext = {extras = ["openai"], version = "^0.4.9.2"}
