[project]
name = "sai-pygame"
version = "0.0.5"
description = "A collection of pygame based minigame environments for the SAI platform."
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "ArenaX Labs", email = "research@competesai.com" }
]
requires-python = ">=3.10"
dependencies = ["gymnasium>=1.0.0", "pygame>=2.1.0", "numpy==1.26.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/sai_pygame"]

[tool.hatch.build]
include = [
    "src/sai_pygame/**/*.py",
    "src/sai_pygame/*/assets/**/*",
    "src/sai_pygame/utils/fonts/*",
]
