[project]
name = "mcp_lightpdf"
version = "0.1.25"
description = "LightPDF文档转换工具"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp",
    "httpx",
    "python-dotenv",
]

[project.scripts]
mcp_lightpdf = "mcp_lightpdf:main"
