[project]
name = "pymodularizer"
version = "0.1.3"
description = "Gerador de projetos Python modularizados"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Hermes A. V. Urquijo", email = "hvurquijo@gmail.com" }
]
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
pymodularizer = "pymodularizer.core.cli:app"

[tool.setuptools.packages.find]
where = ["."]
include = ["pymodularizer*"]
