[tool.poetry]
name = "bunnybase"
version = "0.1.8"
description = "Datamanaging system"
authors = ["trollmii <trollmii@outlook.de>"]
readme = "README.md"
repository = "https://github.com/trollmii/bunnybase"

exclude = [
    "benchmarks/*"
]
[tool.poetry.dependencies]
python = "^3.10"
pyarrow = "^19.0.1"
pandas = "^2.1.0"
numpy = "^2.1.0"
pillow = "^11.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
