[tool.poetry]
name = "md2fileo"
version = "1.3.37"
description = "Yet another file organizer"
repository = "https://github.com/Michal-D4/fileo"
authors = ["mihal.d44 <mihal.d44@gmail.com>"]
readme = "README.md"
packages = [
{include = "fileo.py"},
{include = "src"},
]

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.6.0"
pypdf2 = "^3.0.1"
pyqt6 = "^6.4.0"
apsw = "^3.40.1.0"
markdown = "^3.6"



[tool.poetry.group.dev.dependencies]
lorem = "^0.1.1"
web-pdb = "^1.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
