[tool.black]
skip-string-normalization = true
line-length = 120

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fastapi_swot"
version = "0.0.7"
authors = [
  { name="Harry Dang", email="harrydang.tech@gmail.com" },
]
description = "FastAPI SWOT"
readme = "README.md"
requires-python = ">=3.11.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies=[]

[project.urls]
"Homepage" = "https://github.com/harrylowkey/fastapi_swot"
"Bug Tracker" = "https://github.com/harrylowkey/fastapi_swot/issues"
