[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "onbbu"
version = "0.2.2"
description = "Onbbu ðŸ› ï¸ðŸ â€“ Hexagonal Architecture for Python"
readme = "README.md"
authors = [{ name = "Javier Avila", email = "njavilas2015@gmail.com" }]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "starlette>=0.46.0",    
    "requests>=2.32.3",
    "pydantic>=2.10.6",
    "pytest>=8.3.4",
    "asyncpg>=0.30.0",
    "uvicorn>=0.34.0",
    "aerich>=0.8.2",
    "tortoise-orm>=0.24.1",
    "rich>=13.9.4",
    "etcd3==0.12.0",
    "aiosqlite",
    "typing-extensions",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["onbbu"]  

[tool.setuptools.package-data]
onbbu = ["**/*.pyi"]  

[project.scripts]
onbbu = "onbbu:main"

[project.urls]
"Homepage" = "https://github.com/njavilas2015/onbbu"
"Bug Tracker" = "https://github.com/njavilas2015/onbbu/issues"
