[package]
name = "velatus"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "velatus"
crate-type = ["cdylib"]

[dependencies]
log = "0.4.27"
pyo3 = "0.24.0"
pyo3-log = "0.12.3"
regex = "1.11.1"
