[project]
name = "depgraphviz"
version = "0.1.1"
description = "Creates a graph of the dependencies of a file"
authors = [
    {name = "MichielNijmeijer",email = "michielenn@gmail.com"}
]
license = "MIT"
license-files = ["LICENSE.txt"]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pathlib (>=1.0.1,<2.0.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
depgraphviz = "depgraphviz.main:main"