[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "code-interpreter-mcp-server"
version = "0.1.3"
description = "code-interpreter-mcp-server"
readme = "README.md"
authors = [
    {name = "saikaNya",email = "saikacat@outlook.com"},
]
requires-python = ">=3.11"

dependencies = [
    "mcp[cli]>=1.6.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]


[project.scripts]
code-interpreter-mcp-server = "src.main:main"

[tool.setuptools]
packages = ["src"]