[workspace]
members = ["bindings/*"]

[workspace.package]
version = "0.1.4"
edition = "2021"
authors = ["Michael Barlow <michael.barlow@aleph-alpha-ip.ai>"]
description = "HAT splitter"
repository = "https://github.com/Aleph-Alpha/hat-splitter"
license-file = "LICENSE"
readme = "DOCS.md"

[package]
name = "hat-splitter"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license-file.workspace = true
readme.workspace = true
exclude = [
    ".github/**",
    "/bindings/**",
]
rust-version = "1.81.0"


[dependencies]
icu_segmenter = "1.5.0"
once_cell = "1.21.3"
regex = "1.11.1"
