[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tarp3-nuggets"
dynamic = ["version"]
description = 'A package of nuggets found on the web'
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
keywords = []
authors = [
  { name="Anthony R. Plastino III", email="anthony.r.plastino.iii@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[tool.hatch.version]
path = "src/tarp3_nuggets/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/tarp3_nuggets tests}"

[tool.coverage.run]
source_pkgs = ["tarp3_nuggets", "tests"]
branch = true
parallel = true
omit = [
  "src/tarp3_nuggets/__about__.py",
]

[tool.coverage.paths]
tarp3_nuggets = ["src/tarp3_nuggets", "*/tarp3-nuggets/src/tarp3_nuggets"]
tests = ["tests", "*/tarp3-nuggets/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
